services:

  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT_MYSQL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      
    volumes:
      - mysqldb-volume:/var/lib/mysql

  postgresdb:
    image: postgres
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT_POSTGRESQL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

    volumes:
      - postgresdb-volume:/var/lib/postgressql/data

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${DB_PORT_SQLSERVER:-1435}:1435"

    volumes:
      - sqlserverdb-volume:/var/opt/mssql

volumes:
  mysqldb-volume: {}
  postgresdb-volume: {}
  sqlserverdb-volume: {}
